name: 'Terraform'
on:
  push:
    branches:
      - master


jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    strategy:
      fail-fast: false

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout Repo
      uses: actions/checkout@v2

    
    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.


    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESSKEYID }}
        aws-secret-access-key: ${{ secrets.ACCESSKEY }}
        aws-region: us-east-1
    # Generates an execution plan for Terraform
    # - name: Terraform Format
    #   run: terraform fmt -recursive

    - name: Terraform Plan
      run: terraform plan

    # - name: Terraform Apply
    #   run: terraform apply -auto-approve